image: docker:latest

stages:
  - test
  - build

services:
  - docker:dind

.test:
  stage: test
  script:
    - docker build .
  tags: [docker]

.test tag:
  extends: .test
  script:
    - docker build --build-arg PHP_VERSION=$TAG .

.build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  tags: [docker]

.build tag:
  extends: .build
  script:
    - docker build --build-arg PHP_VERSION=$TAG -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG

test 5.6:
  extends: .test tag
  variables:
    TAG: "5.6"

test 7.0:
  extends: .test tag
  variables:
    TAG: "7.0"

test 7.1:
  extends: .test tag
  variables:
    TAG: "7.1"

test 7.2:
  extends: .test tag
  variables:
    TAG: "7.2"

test 7.3:
  extends: .test tag
  variables:
    TAG: "7.3"

build 5.6:
  extends: .build tag
  variables:
    TAG: "5.6"

build 7.0:
  extends: .build tag
  variables:
    TAG: "7.0"

build 7.1:
  extends: .build tag
  variables:
    TAG: "7.1"

build 7.2:
  extends: .build tag
  variables:
    TAG: "7.2"

build 7.3:
  extends: .build tag
  variables:
    TAG: "7.3"
