image: docker:latest

services:
  - docker:dind

.build:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$PHP_VERSION .
    - docker push $CI_REGISTRY_IMAGE:PHP_VERSION
  only: [main]
  tags: [docker]

build latest:
  extends: .build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags: [docker]

.build tag:
  extends: .build
  script:
    - docker build --build-arg PHP_VERSION=$TAG -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG

build 7.4:
  extends: .build tag
  variables:
    TAG: "7.4"

build 8.0:
  extends: .build tag
  variables:
    TAG: "8.0"

build 8.1:
  extends: .build tag
  variables:
    TAG: "8.1"

build 8.2:
  extends: .build tag
  variables:
    TAG: "8.1"
